// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id
) VALUES ($1) RETURNING id, slug, audio_url
`

func (q *Queries) CreatePost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, id)
	var i Post
	err := row.Scan(&i.ID, &i.Slug, &i.AudioUrl)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, slug, audio_url FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(&i.ID, &i.Slug, &i.AudioUrl)
	return i, err
}

const getPostLike = `-- name: GetPostLike :one
SELECT user_id, post_id, created_at FROM post_saves
WHERE user_id = $1 AND post_id = $2
`

type GetPostLikeParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) GetPostLike(ctx context.Context, arg GetPostLikeParams) (PostSafe, error) {
	row := q.db.QueryRowContext(ctx, getPostLike, arg.UserID, arg.PostID)
	var i PostSafe
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const getPostSave = `-- name: GetPostSave :one
SELECT user_id, post_id, created_at FROM post_saves
WHERE user_id = $1 AND post_id = $2
`

type GetPostSaveParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) GetPostSave(ctx context.Context, arg GetPostSaveParams) (PostSafe, error) {
	row := q.db.QueryRowContext(ctx, getPostSave, arg.UserID, arg.PostID)
	var i PostSafe
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const getUserSaves = `-- name: GetUserSaves :many
SELECT user_id, post_id, created_at FROM post_saves
WHERE user_id = $1
ORDER BY created_at
LIMIT $2
OFFSET $3
`

type GetUserSavesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetUserSaves(ctx context.Context, arg GetUserSavesParams) ([]PostSafe, error) {
	rows, err := q.db.QueryContext(ctx, getUserSaves, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostSafe{}
	for rows.Next() {
		var i PostSafe
		if err := rows.Scan(&i.UserID, &i.PostID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likePost = `-- name: LikePost :one
INSERT INTO post_likes (
    user_id,
    post_id
) VALUES($1, $2) RETURNING user_id, post_id, created_at
`

type LikePostParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (PostLike, error) {
	row := q.db.QueryRowContext(ctx, likePost, arg.UserID, arg.PostID)
	var i PostLike
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, slug, audio_url FROM posts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(&i.ID, &i.Slug, &i.AudioUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserLikes = `-- name: RemoveAllUserLikes :exec
DELETE FROM post_likes WHERE user_id = $1
`

func (q *Queries) RemoveAllUserLikes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeAllUserLikes, userID)
	return err
}

const removeAllUserSaves = `-- name: RemoveAllUserSaves :exec
DELETE FROM post_saves WHERE user_id = $1
`

func (q *Queries) RemoveAllUserSaves(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeAllUserSaves, userID)
	return err
}

const removeLikePost = `-- name: RemoveLikePost :exec
DELETE FROM post_likes 
WHERE user_id = $1 AND post_id = $2
`

type RemoveLikePostParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) RemoveLikePost(ctx context.Context, arg RemoveLikePostParams) error {
	_, err := q.db.ExecContext(ctx, removeLikePost, arg.UserID, arg.PostID)
	return err
}

const removeSavePost = `-- name: RemoveSavePost :exec
DELETE FROM post_saves AS p 
WHERE p.user_id = $1 AND p.post_id = $2
`

type RemoveSavePostParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) RemoveSavePost(ctx context.Context, arg RemoveSavePostParams) error {
	_, err := q.db.ExecContext(ctx, removeSavePost, arg.UserID, arg.PostID)
	return err
}

const savePost = `-- name: SavePost :one
INSERT INTO post_saves (
    user_id,
    post_id
) VALUES($1, $2) RETURNING user_id, post_id, created_at
`

type SavePostParams struct {
	UserID string `json:"user_id"`
	PostID string `json:"post_id"`
}

func (q *Queries) SavePost(ctx context.Context, arg SavePostParams) (PostSafe, error) {
	row := q.db.QueryRowContext(ctx, savePost, arg.UserID, arg.PostID)
	var i PostSafe
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const updatePostAudio = `-- name: UpdatePostAudio :one
UPDATE posts
SET audio_url = $2
WHERE id = $1
RETURNING id, slug, audio_url
`

type UpdatePostAudioParams struct {
	ID       string         `json:"id"`
	AudioUrl sql.NullString `json:"audio_url"`
}

func (q *Queries) UpdatePostAudio(ctx context.Context, arg UpdatePostAudioParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePostAudio, arg.ID, arg.AudioUrl)
	var i Post
	err := row.Scan(&i.ID, &i.Slug, &i.AudioUrl)
	return i, err
}
